Added Indent code functionality with Tab key and Unit tested the Tab key
chingu-voyage4/Bears-Team-7 pull request #25
Opened 2018-03-20 13:16 UTC by jayrexacilo

- Added two spaces "\xa0\xa0" when Indenting the code on Tab key
- Resolve issue #15

2018-03-20 21:55 UTC, Matthew-Burfield requested changes
Yeah I'm happy with the double space solution, it's better than having inconsistency in the spacing. We can potentially do a spaces vs tabs setting later on.

Just one thing with the tests, each test should only test one thing. We already have tests that test "abc123" and enter etc. So in your test, could you update it so it only triggers the tab key?

2018-03-21 13:27 UTC, jayrexacilo commented
.text() api removes extra spaces. so when i test it, it'll fail. see image

![abc-tab-test](https://user-images.githubusercontent.com/31985700/37712348-96de917a-2d4e-11e8-8f55-7d9d82977512.png)
![tab-test](https://user-images.githubusercontent.com/31985700/37712349-9795890c-2d4e-11e8-8cca-daa71e352d5f.png)

2018-03-21 22:19 UTC, Matthew-Burfield commented
You're totally right @jayrexacilo @ajayrexluega 

You're totally right that .text() trims strings, I'm not sure the best way to test this then - potentially we could use the .html() and check that it contains two spaces?

Otherwise, I've added a test that checks the documentData object directly (not usually good practice as it's testing the implementation details of the Vue component as opposed to the end result the user sees)

Anyway, what do you think?

2018-03-21 22:21 UTC, Matthew-Burfield approved these changes

2018-03-23 11:59 UTC, merged