Fix backspace key
chingu-voyage4/Bears-Team-7 pull request #51
Opened 2018-04-06 05:41 UTC by AlysCole

Fix the behavior of the backspace key, wherein when the caret is at
the beginning of an existing line, nothing is done. When pressed with
the caret at the beginning of a line, the backspace key should now
combine the current line and previous line at the previous row.

Close issue #49.

2018-04-06 09:34 UTC, Matthew-Burfield commented
There is an issue were if the caret is at the very start of the document (the start of line 1), and there are other lines (lines 2, 3, 4 etc), then pressing backspace deletes lines 2, 3, 4 etc instead of stopping at line 1.

Also, if you do it quickly, the caret actually disappears all together giving this error:

2018-04-06 09:43 UTC, Matthew-Burfield requested changes
.

2018-04-07 14:38 UTC, AlysCole commented
@Matthew-Burfield Woops! Looks like it was deleting the last elements of `documentData`.

The commit fe5821a should fix this.

2018-04-07 20:12 UTC, Matthew-Burfield approved these changes
Woo that fixed it. Nice work!

2018-04-09 02:44 UTC, merged